spring:
  application:
    name: ecom
  datasource:
#        url: jdbc:oracle:thin:@//localhost:1521/orcl
#        username: hr
#        password: hr
#        driver-class-name: oracle.jdbc.OracleDriver
#    url: jdbc:oracle:thin:@//green.maxapex.net:1555/XEPDB1
#    username: A234491B
#    password: XFS934PK5R2X
#    driver-class-name: oracle.jdbc.OracleDriver
      url: jdbc:postgresql://dpg-d206rcfgi27c73c7v2pg-a.frankfurt-postgres.render.com:5432/ecomdb_6fzy
      username: ecomdb_6fzy_user
      password: LuSIO6zenqtkW6GyscbW98emyydMqUFr
      driver-class-name: org.postgresql.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

  cache:
    type: caffeine
    caffeine:
      spec: maximumSize=100,expireAfterWrite=30s

server:
  port: 8080

twilio:
  account:
    sid: ACbfd97d6d8a249d013fdc77d71dcd1d06
  auth:
    token: d7c4e8260999f834c8bb699eec5b14c8
  whatsapp:
    from: whatsapp:+14155238886

jwt:
  secret: Vg#r82mWz&1Lq$9d!ApBkE6sTfYhN0X3CuMzQaJvPoR7UcXs
  accessExpiration: 2592000 # (1 ساعة)
  refreshExpiration: 2592000 # (1 ساعة)



#security:
#  jwt:
#    secret-key: 3cfa76ef14937c1c0ea519f8fc057a80fcd04a7420f8e8bcd0a7567c272e007b
#   expiration-time: 3600000  # 1 hour in milliseconds
#
#logging:
#  level:
#    org.springframework: DEBUG

